# Generated by Django 4.2.20 on 2025-05-06 18:44

from django.db import migrations
from decimal import Decimal

def fill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')

    for item in OrderItem.objects.filter(price__isnull=True).select_related('product'):
        item.price = item.product.price
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_prices, reverse_code=migrations.RunPython.noop),
    ]
