# Generated by Django 4.2.20 on 2025-05-07 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_options_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('online', 'Электронно')], db_index=True, default='не доставлено', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 7, 13, 2, 10, 270869, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('raw', 'Необработанный'), ('in_progress', 'Отправлен на сборку'), ('in_delivery', 'Отправлен на доставку'), ('completed', 'Выполнен')], db_index=True, default='raw', max_length=20, verbose_name='статус'),
        ),
    ]
