# Generated by Django 4.2.20 on 2025-05-07 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_method_alter_order_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('online', 'Электронно')], db_index=True, default='не оплачено', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 7, 13, 9, 14, 523644, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
