# Generated by Django 4.2.20 on 2025-05-07 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_payment_method_alter_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 7, 15, 42, 34, 704517, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
