# Generated by Django 4.2.20 on 2025-05-13 18:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_location_remove_order_lat_remove_order_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 13, 18, 29, 44, 764704, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
