# Generated by Django 3.2.15 on 2025-06-11 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_registered_at_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 6, 11, 16, 12, 31, 344452, tzinfo=utc), verbose_name='дата создания'),
        ),
    ]
